---
- name: Update and upgrade apt packages
  apt:
    upgrade: yes
    update_cache: yes

- name: Install common packages
  apt:
    name:
      - git
      - vim
      - curl
      - wget
      - tig
    state: present